### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by Bost** [Toxyl/corona#6]
In the console I get
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
jquery.js:3429:51
SyntaxError: bad method definition CoronaTracker.js:3:8
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. corona
```
However it works fine in google chrome. 

Also, please add there a column with country codes so I don't need to type so much if I want to check the numbers say several times per day.

**Comment by Toxyl** [comment]
I came across that today as well, I'll look into it.
Will add country codes too. Btw, you only need to make your selection once (you can use the URL above the table for a bookmark), the data will be updated automatically every 15 minutes, no need for a manual refresh.

**Comment by Toxyl** [comment]
I fixed two issues related to Firefox, should work properly now.
I've also added country codes you can use for filtering, examples from the updated README:
- `Neth,Erman` will show `*Neth*erlands [NL]` and `G*erman*y [DE]`
- `[NL],Erman` will show `Netherlands *[NL]*` and `G*erman*y [DE]`
- `[Z` will show `South Africa *[Z*A]`, `Zambia *[Z*M]` and `Zimbabwe *[Z*W]`
